# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md

---
- name: Bootstrapping Nginx proxy for healthz check
  hosts: all
  become: true
  gather_facts: false
  vars:
    user: appuser

  tasks:

  - name: Install Nginx
    apt:
      name: ['nginx']
      state: present
      update_cache: yes

  - name: Copy template scripts
    template:
      src: templates/{{ item }}
      dest: /home/{{ user }}/{{ item | replace('.j2','') }}
      mode: 0755
    with_items:
      - kubernetes.default.svc.cluster.local.sh.j2

  - name: Make services and configs
    shell: /home/{{ user }}/{{ item }}
    with_items:
      - kubernetes.default.svc.cluster.local.sh

  - name: Daemon reload
    systemd:
      daemon_reload: yes

  - name: Enable services and start it
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - nginx

  - name: Raw result of running verification command for proxy healthz check
    shell: 'curl -s -H "Host: kubernetes.default.svc.cluster.local" -i http://127.0.0.1/healthz'
    register: output_result

  - name: Save output_result to local file
    local_action: copy content={{ output_result }} dest=logs/nginx-healthz-verification-{{ inventory_hostname }}


