stages:
  - build
  - test
  - review
  - stage
  - prod

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  #- docker info
  #- cd reddit
  #- bundle install

build_job:
  stage: build
  image: docker:git
  services:
    - docker:dind
  build:
    script:
      - echo 'Building'
      - cd reddit-app-docker
      - docker build -t reddit-app .
      - docker push reddit-app
  tags:
   - docker

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - cd reddit
    - bundle install
    - ruby simpletest.rb
  tags:
   - docker

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com
  tags:
   - docker

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
  tags:
   - docker

staging:
  stage: stage
  when: manual
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com
  tags:
   - docker

production:
  stage: prod
  when: manual
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
  tags:
   - docker
