stages:
  - build
  - test
  - review
  - stage
  - prod

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker info

build_job:
  stage: build
  script:
  - echo 'Building'
  - cd reddit
  - docker build -t reddit-app .
  - docker push reddit-app
  tags:
  - docker

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - cd reddit
    - bundle install
    - ruby simpletest.rb
  tags:
  - ruby

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com
  tags:
  - ruby

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
  tags:
   - ruby

staging:
  stage: stage
  when: manual
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com
  tags:
   - ruby

production:
  stage: prod
  when: manual
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
  tags:
   - ruby
