dist: trusty
language: bash
sudo: required
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: V7BfspdRIHiFxLAZO1Du0YAkCs7DW0ftISge05BUbgn5wZqI/8/xkApvWJtMalJ8Q7GwLTv3A3mTXHpm8rVSplYeOBy05vflQWgbwKG79JKWDIq4t9ah5Fzk90KbJr4qa9EDdpQskch+FuKkI5duHaKgCZkynvPVjGY2pKN9ypIz1NUxnhPKz1WH+UH6niEu8rN69Yc4GAvilZKIGsLXnVUO/Uf08M3DW5Gkhr2c9na40QmBIHPCRP49bc2qXplXHu3OjLHNCgR6WlNmhWEbQKbOzwwi9Y/q8uxAYwHS/rMWMfbNvF+v+6DWLJd0NhXRk2jsLg5ZOE7XxoTKMlcvgcgXGzQj3zccReQoNKZwYRKVRo8eXiqBfrFKkhjc89/MUU4/vATVUTqQm487iOer0DS2d47x/ZldQV+jmBcsFodNSIxTujfGOopCk/OiEi+vxYnxkFjAYOzFnQ4CZYzkRqXC7kxK8Q7rhbvfUiWR4zK9XMhxZ6qMlvGK64aMuBHhuQestLMwGU6SYiLJxGqs7FSG3H7A5pVwLbTcwfFI0UMhfW6M4MiteZZLMDHjPQqUPzICjzJEFFuKBbr+Ehc+z2smmBjYVj46LJwNZOL/enlrKCOyl8Eqs9MyN3SOuKxocv94Ms24cvtJ3LjeVlbhBQ1A/t0M8hj6b4LEuZw/n9s=
