dist: trusty
language: bash
sudo: required
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: Y5mPVx6zt96dRU4jfewrryAUMqvNT10Ez7JvaejHCrdUvVSoKNUh8CeEzWSV9qWG6ak6As1njjjWI0rJODnFkbviSif+UXhCNYEPQPvfUtQ8/Wuht8pmnpgm9P5M8kVF8+uQFgZNIY84AOp9XMdmWUE1sMeac0X0vqQW2yBrSl3eGPn0FAHrgKhIqAE4ANtTbRHoDJh01F1fdSAnKDznl0hXlkY+2BRBBkzX7KX2EM+EwekQ8mnHU/gP1viBSckDztiw+OIsaUB68iUw/9BRT5dSScw4aJQW5oYVIm5KG/PfpcwbK5ESovs/LPDvoIraW74zQd9g8qBw0nNiER61Xzvjpi4pzk0vNhySbj7r3g0pT3NQq142xrIR/s79FHC9+a1g7ckdYqBKzeCEO9PcJVAXrJimM0DSJxQhw6as5zmplD25aDFNDzAM1GP9o+ayC7AkFkSSGDua34qNxLPWFNHWG8+MfGpC6tsM2OC0BZLCIhU3dSdghuvslHq37zrZnnxvEDb/lD4zHF4J/QI1wm5Ev4jLiz1IeLUZrLzziUZFS/nvto3Lu5TNHB4VOBT8EDTC3lh796ir3z3DLtSy4aIdzPz+aRnvWr1Y/kxt/fBmGAHb35llQY8tZHQWQJ/5MdXLZCTbfCN6zAoF4lc+XUKFpaarQOKRFUKdmoG83sc=
