dist: trusty
language: bash
sudo: required
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: DyxQ6cJrqDh37DmFCKMdg+TfKGI16Ti3BZyUfFg7pY/edD2M7fmOjY1N3S7Xq3SvqYYb0jLuHx7g1FsdVtOTF95Wha/QN9h6wrFlGEsItRJSa9lwyHTPaC78lk5bpShCi6djdLsd/akNuoktuxuyZdhQCmFIvpwGY1rdetq19JVRhpvI09tJVRU+EonLF/7YeQkATot3qfClU9iN3n94spwOfkp7MzXSzvgwIujOosoGBRu+x9Iu3dAQ7WDBDMDXIAvYEMaOhu/+bVNA0iBiRtRJejJKBv/K04PqCpt4/0VnRBgzeL+gCtQ8RxvRY1jmuCM99VBbzN0euYOwOF9Oo11LMFR46X4deUxhVRZFUxdKo6Ss5fLcu3X10bIWPZmMaXRxp+wBTFx4wXWb2x9MMzBqAYkBNCYgU6qlrpy1EEJ4IpIFDum+mJ/r7aa8FmB4rW9xV+NgObWGdNvBr0XztQQm+UK3oJDyXEj7QhFf8Rm7+vLGyk36p/BH93Z+OQRfCB04kwX607KdeRqDOB9yfI2mXKY4fW6Udwv8qbBx2AU7sFgG45bdjx66r6JsENGGt9mujdddwn3DsIhAEPzjOFEgDWj+Vdivwkd/xNHqYTWhmy7fMYu5ahjPzPGDZIlB+2mRlIvBIgvmxVzZf6R8pEn/fAR+I8tOF6dtbLLyvqo=
