dist: trusty
language: bash
sudo: required
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh | bash
notifications:
  slack:
    secure: aCdXHyRN7dCpJOWioRPiZfdYf/vazTn9zleqFA4I5q0qgJsxu5O9wkX5qDHbsQClu4FCqXbZuLhywR/bZxgxeBJYaJZGIyl+7kjpjAkoYATulz8BY1ckSUSO8Yru3OGfDQvSRQHiuzpgjNrdtEagoo/5bpjymrVlbEM3K1xU78jYRu88TgLedWNfregL5Qe6wYhZTZ8haJ8K/s+iYHfRx1Q33iS6bB7EKUHKQr9l1IsBjbhoiKvFHh3Zdbvd6IoRKRgHyy7rNzFNJTt46ir0Cz0G+v2nwj2IE/tdFwhVVBsL3876kBRl+1ULFjfm6TGb2u/+GJ2khSZ5rTJFKESI3ZSpAsJoNNJGIiwSlp6ablIdrIgNZLCj7nEiPsRKOwKpQ04mw4htdDqqW6mrj/LGZok/H8JbPeqB6qcG6bQplqqwgUHQSZXrVjE5k8ff2ItoBPrldwiLmX2Q8sO+kzmG3fm4AMC/Awt6bsDIrzms7LG/bQqGcLF9m9N0clui940Q8GI+W97oOzNIK1w00YcEiUq/aGKl0gobJd4sXv5VmgJWKjV+70Ly0o5i9PbXCwG5z7meVVIT91pxDjMrK0lXs1RDfzgDLuNbhVA2ABWg7ePftnH99SIqsQkRT1ReGqHIad6cQHVpHxIGz7d8eAUDI5gJWM2QyKUZvF3kbF1/U5A=
