dist: trusty
language: bash
sudo: required
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: RAWGRYafcl9e2qmFRpWmWrjGco1lDDmIQGfn2f5vLNiUrfQOKpmFLm0+r5nCxd+jnVcZwdlXcPULdLo37F2A2psM/kH9CTEefO8fXNTqpvYq8hUZfMqnAbq1VtOAMQtt909jl0JbXSnHwOJAR7RliFHtyfV4QSzyocW5z5hETH+P/XmlxY8sHu6kMSm4L2LsQTsGVQna8+MaSaaVkteAjw+fo0VKqfzR7Riicjhmn1/VdXu51qOJ3xlDzM4Cduon0R6E7HNDFarX3JVE1DrCAEdCqQjNchXqdzdKxodvbz6QFiFlMwRfjzsx9ySJ4ohIHMhJtBaPeZwj9SnsqJbz2fz89akkX0zEXQEjUtUUkVzf/REYRulJMOkpoqiTSxJQvE7pvS+9AeDQZByQa6Sk/DERCf6ptWZJEnU/jalQuHn9zpEouoTGj88MIGpAcX8WT17IUXEo03SiF7j0Vh2uF7QP8jerAWB8REW52icNoktArhzH/HmqPhuAtgeLn+tqMU1aMvYCuJqahvqDWpK4G+3oGqao5Zc4HI4fjPyz44/4ioTShcCVHPTzoFcA5Uo8qvwaMC2yeaepdRsCnXneGKU2QOHsqCN34mRImx/gpYt9F9YLBVLjM0bHg1qmRN/1qZUmB10o0VoaU13xYQboHAYZBgAWwuiIja818ZHtfdc=
