FROM ruby:2.2

ENV APP_HOME /app
COPY . $APP_HOME
WORKDIR $APP_HOME

RUN apt-get update -qq \
&& apt-get install -y build-essential \
&& bundle install

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
